name: ai-agentx-release

on:
  release:
    types:
      - created

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux
            arch: x64
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Checkout tag
        run: git checkout ${GITHUB_REF#refs/tags/}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Docker image
        run: docker build -f backend/Dockerfile -t craftslab/coze-studio:latest .
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push Docker image
        run: docker push craftslab/coze-studio:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Copy model config template
        run: cp backend/conf/model/template/model_template_gemini.yaml backend/conf/model/gemini.yaml
      - name: Copy .env file
        run: cd docker && cp .env.example .env
      - name: Install Railway CLI
        run: npm install -g railway
      - name: Deploy to Railway
        run: railway up --service coze-studio
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
